CONFIG_PROJECT_DEXATEK_ESG := 1
CONFIG_PROJECT_BUIMA_EMS := 2
CONFIG_PROJECT_HITACHI_EMS := 3
CONFIG_PROJECT_COMMON_EMS := 4
CONFIG_PROJECT_ID := 1

CONFIG_PROJECT_DEXATEK_ESG_MINOR_VERSION := 0
CONFIG_PROJECT_COMMON_EMS_MINOR_VERSION := 1
CONFIG_PROJECT_HITACHI_EMS_MINOR_VERSION := 97
CONFIG_PROJECT_BUIMA_EMS_MINOR_VERSION := 98
CONFIG_PROJECT_DEXATEK_ESG_LOCAL_MINOR_VERSION := 99
