#ifndef MODBUS_MANAGER_CONFIG_H
#define MODBUS_MANAGER_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define MODBUS_MANAGER_CONFIG_BAUDRATE_DEFAULT  MODBUS_MANAGER_CONFIG_BAUDRATE_115200
#define MODBUS_MANAGER_CONFIG_DATABIT_DEFAULT   MODBUS_MANAGER_CONFIG_DATABIT_8BIT
#define MODBUS_MANAGER_CONFIG_PARITY_DEFAULT    MODBUS_MANAGER_CONFIG_PARITY_NONE
#define MODBUS_MANAGER_CONFIG_STOPBIT_DEFAULT   MODBUS_MANAGER_CONFIG_STOPBIT_1BIT

typedef enum {
	MODBUS_MANAGER_DATA_TYPE_INT16,
	MODBUS_MANAGER_DATA_TYPE_UINT16,
    MODBUS_MANAGER_DATA_TYPE_INT32,
    MODBUS_MANAGER_DATA_TYPE_UINT32,
    MODBUS_MANAGER_DATA_TYPE_FLOAT32,
    MODBUS_MANAGER_DATA_TYPE_UINT64,
    MODBUS_MANAGER_DATA_TYPE_MAX,
} MODBUS_MANAGER_CONFIG_DATA_TYPE;

typedef enum {
	MODBUS_MANAGER_CONFIG_DATA_ENDIAN_BIG,
	MODBUS_MANAGER_CONFIG_DATA_ENDIAN_LITTLE,
    MODBUS_MANAGER_CONFIG_DATA_ENDIAN_MAX
} MODBUS_MANAGER_CONFIG_DATA_ENDIAN;

typedef enum {
	MODBUS_MANAGER_CONFIG_BAUDRATE_9600,
    MODBUS_MANAGER_CONFIG_BAUDRATE_19200,
    MODBUS_MANAGER_CONFIG_BAUDRATE_38400,
    MODBUS_MANAGER_CONFIG_BAUDRATE_57600,
    MODBUS_MANAGER_CONFIG_BAUDRATE_115200,
} MODBUS_MANAGER_CONFIG_BURARATE_IDX;

typedef enum {
	MODBUS_MANAGER_CONFIG_DATABIT_8BIT,
	MODBUS_MANAGER_CONFIG_DATABIT_7BIT,
} MODBUS_MANAGER_CONFIG_DATABIT_IDX;

typedef enum {
	MODBUS_MANAGER_CONFIG_PARITY_NONE,
	MODBUS_MANAGER_CONFIG_PARITY_ODD,
    MODBUS_MANAGER_CONFIG_PARITY_EVEN,
} MODBUS_MANAGER_CONFIG_PARITY_IDX;

typedef enum {
	MODBUS_MANAGER_CONFIG_STOPBIT_1BIT,
	MODBUS_MANAGER_CONFIG_STOPBIT_2BIT,
} MODBUS_MANAGER_CONFIG_STOPBIT_IDX;

#ifdef __cplusplus
}
#endif

#endif
