#ifndef MODBUS_MANAGER_H
#define MODBUS_MANAGER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "dexatek/main_application/managers/modbus_manager/modbus_manager_config.h"

#include "dexatek/main_application/managers/hid_manager/dk_modbus_gpio.h"
#include "dexatek/main_application/managers/hid_manager/dk_modbus_ad74416h.h"
#include "dexatek/main_application/managers/hid_manager/dk_modbus_pwm.h"
#include "dexatek/main_application/managers/hid_manager/dk_modbus_cap_pwm.h"
#include "dexatek/main_application/managers/hid_manager/dk_modbus_setting.h"
#include "dexatek/main_application/managers/hid_manager/dk_modbus_ad7124.h"

#include <modbus.h>

/**
 * Structure containing modbus parameters and context
 */
typedef struct modbus_param_t {
    modbus_t *ctx;                  /**< Modbus context */
    modbus_mapping_t *data_mapping; /**< Modbus data mapping */
    uint8_t role;                   /**< Role (master/slave) */
    uint8_t baudrateIndex;          /**< Baudrate index */
    uint8_t databitIndex;           /**< Data bits index */
    uint8_t parityIndex;            /**< Parity index */
    uint8_t stopbitIndex;           /**< Stop bits index */
} modbus_param;

#define MODBUS_SERIAL_PARITY        'N'     /* 'N', 'E', or 'O' */
#define MODBUS_SERIAL_DATABITS      8       /* 5, 6, 7, or 8 */
#define MODBUS_SERIAL_STOPBITS      1       /* 1 or 2 */
#define MODBUS_DEVICE_ID            100
#define MODBUS_TIMEOUT_SEC          3
#define MODBUS_TIMEOUT_USEC         0
#define MODBUS_DEBUG                ON
#define MODBUS_RO_BITS              16
#define MODBUS_RW_BITS              16
#define MODBUS_RO_REGISTERS         20000
#define MODBUS_RW_REGISTERS         128

#define HID_IO_BOARD_BASE_ADDRESS 100
#define HID_RTD_BOARD_BASE_ADDRESS 1000

#define HID_BASE_ADDRESS 11000
#define HID_BASE_ADDRESS_RTD 11500

typedef enum {
    MODBUS_ADDRESS_GPIO_OUTPUT_0 = 1,
    MODBUS_ADDRESS_GPIO_OUTPUT_1 = 2,
    MODBUS_ADDRESS_GPIO_OUTPUT_2 = 3,
    MODBUS_ADDRESS_GPIO_OUTPUT_3 = 4,
    MODBUS_ADDRESS_GPIO_OUTPUT_4 = 5,
    MODBUS_ADDRESS_GPIO_OUTPUT_5 = 6,
    MODBUS_ADDRESS_GPIO_OUTPUT_6 = 7,
    MODBUS_ADDRESS_GPIO_OUTPUT_7 = 8,
    MODBUS_ADDRESS_GPIO_INPUT_0 = 9,
    MODBUS_ADDRESS_GPIO_INPUT_1 = 10,
    MODBUS_ADDRESS_GPIO_INPUT_2 = 11,
    MODBUS_ADDRESS_GPIO_INPUT_3 = 12,
    MODBUS_ADDRESS_GPIO_INPUT_4 = 13,
    MODBUS_ADDRESS_GPIO_INPUT_5 = 14,
    MODBUS_ADDRESS_GPIO_INPUT_6 = 15,
    MODBUS_ADDRESS_GPIO_INPUT_7 = 16,
    MODBUS_ADDRESS_AD74416H_CH_A_SET_MODE = 17,
    MODBUS_ADDRESS_AD74416H_CH_B_SET_MODE = 18,
    MODBUS_ADDRESS_AD74416H_CH_C_SET_MODE = 19,
    MODBUS_ADDRESS_AD74416H_CH_D_SET_MODE = 20,
    MODBUS_ADDRESS_AD74416H_CH_A_VOLTAGE_OUT_MAX_CURRENT = 21,
    MODBUS_ADDRESS_AD74416H_CH_B_VOLTAGE_OUT_MAX_CURRENT = 23,
    MODBUS_ADDRESS_AD74416H_CH_C_VOLTAGE_OUT_MAX_CURRENT = 25,
    MODBUS_ADDRESS_AD74416H_CH_D_VOLTAGE_OUT_MAX_CURRENT = 27,
    MODBUS_ADDRESS_AD74416H_CH_A_CURRENT_INPUT_MAX_CURRENT = 29,
    MODBUS_ADDRESS_AD74416H_CH_B_CURRENT_INPUT_MAX_CURRENT = 31,
    MODBUS_ADDRESS_AD74416H_CH_C_CURRENT_INPUT_MAX_CURRENT = 33,
    MODBUS_ADDRESS_AD74416H_CH_D_CURRENT_INPUT_MAX_CURRENT = 35,
    MODBUS_ADDRESS_AD74416H_CH_A_VOLTAGE_OUTPUT_V = 37,
    MODBUS_ADDRESS_AD74416H_CH_B_VOLTAGE_OUTPUT_V = 39,
    MODBUS_ADDRESS_AD74416H_CH_C_VOLTAGE_OUTPUT_V = 41,
    MODBUS_ADDRESS_AD74416H_CH_D_VOLTAGE_OUTPUT_V = 43,
    MODBUS_ADDRESS_AD74416H_CH_A_CURRENT_OUTPUT = 45,
    MODBUS_ADDRESS_AD74416H_CH_B_CURRENT_OUTPUT = 47,
    MODBUS_ADDRESS_AD74416H_CH_C_CURRENT_OUTPUT = 49,
    MODBUS_ADDRESS_AD74416H_CH_D_CURRENT_OUTPUT = 51,
    MODBUS_ADDRESS_AD74416H_CH_A_VOLTAGE = 53,
    MODBUS_ADDRESS_AD74416H_CH_B_VOLTAGE = 55,
    MODBUS_ADDRESS_AD74416H_CH_C_VOLTAGE = 57,
    MODBUS_ADDRESS_AD74416H_CH_D_VOLTAGE = 59,
    MODBUS_ADDRESS_AD74416H_CH_A_CURRENT = 61,   
    MODBUS_ADDRESS_AD74416H_CH_B_CURRENT = 63,
    MODBUS_ADDRESS_AD74416H_CH_C_CURRENT = 65,
    MODBUS_ADDRESS_AD74416H_CH_D_CURRENT = 67,

    MODBUS_ADDRESS_BOARD_A_USB_VID = 90,
    MODBUS_ADDRESS_BOARD_A_USB_PID = 91,

    MODBUS_ADDRESS_SET_BAUDRATE = 500,
    MODBUS_ADDRESS_SET_DATABITS = 501,
    MODBUS_ADDRESS_SET_PARITY = 502,
    MODBUS_ADDRESS_SET_STOPBITS = 503,
    MODBUS_ADDRESS_SET_PWM_FREQ = 504,
    MODBUS_ADDRESS_SET_PWM_0_DUTY = 506,
    MODBUS_ADDRESS_SET_PWM_1_DUTY = 507,
    MODBUS_ADDRESS_SET_PWM_2_DUTY = 508,
    MODBUS_ADDRESS_SET_PWM_3_DUTY = 509,
    MODBUS_ADDRESS_SET_PWM_4_DUTY = 510,
    MODBUS_ADDRESS_SET_PWM_5_DUTY = 511,
    MODBUS_ADDRESS_SET_PWM_6_DUTY = 512,
    MODBUS_ADDRESS_SET_PWM_7_DUTY = 513,
    MODBUS_ADDRESS_CAPTURE_PWM_0_DUTY = 514,
    MODBUS_ADDRESS_CAPTURE_PWM_1_DUTY = 515,
    MODBUS_ADDRESS_CAPTURE_PWM_2_DUTY = 516,
    MODBUS_ADDRESS_CAPTURE_PWM_3_DUTY = 517,
    MODBUS_ADDRESS_CAPTURE_PWM_4_DUTY = 518,
    MODBUS_ADDRESS_CAPTURE_PWM_5_DUTY = 519,
    MODBUS_ADDRESS_CAPTURE_PWM_6_DUTY = 520,
    MODBUS_ADDRESS_CAPTURE_PWM_7_DUTY = 521,
    MODBUS_ADDRESS_CAPTURE_PWM_0_FREQ = 522,
    MODBUS_ADDRESS_CAPTURE_PWM_1_FREQ = 524,
    MODBUS_ADDRESS_CAPTURE_PWM_2_FREQ = 526,
    MODBUS_ADDRESS_CAPTURE_PWM_3_FREQ = 528,
    MODBUS_ADDRESS_CAPTURE_PWM_4_FREQ = 530,
    MODBUS_ADDRESS_CAPTURE_PWM_5_FREQ = 532,
    MODBUS_ADDRESS_CAPTURE_PWM_6_FREQ = 534,
    MODBUS_ADDRESS_CAPTURE_PWM_7_FREQ = 536,
    MODBUS_ADDRESS_CAPTURE_PWM_0_PERIOD = 538,
    MODBUS_ADDRESS_CAPTURE_PWM_1_PERIOD = 540,
    MODBUS_ADDRESS_CAPTURE_PWM_2_PERIOD = 542,
    MODBUS_ADDRESS_CAPTURE_PWM_3_PERIOD = 544,
    MODBUS_ADDRESS_CAPTURE_PWM_4_PERIOD = 546,
    MODBUS_ADDRESS_CAPTURE_PWM_5_PERIOD = 548,
    MODBUS_ADDRESS_CAPTURE_PWM_6_PERIOD = 550,
    MODBUS_ADDRESS_CAPTURE_PWM_7_PERIOD = 552,
    MODBUS_ADDRESS_AD7124_CH_0_RESISTOR = 554,
    MODBUS_ADDRESS_AD7124_CH_1_RESISTOR = 556,
    MODBUS_ADDRESS_AD7124_CH_2_RESISTOR = 558,
    MODBUS_ADDRESS_AD7124_CH_3_RESISTOR = 560,
    MODBUS_ADDRESS_AD7124_CH_4_RESISTOR = 562,
    MODBUS_ADDRESS_AD7124_CH_5_RESISTOR = 564,
    MODBUS_ADDRESS_AD7124_CH_6_RESISTOR = 566,
    MODBUS_ADDRESS_AD7124_CH_7_RESISTOR = 568,
    MODBUS_ADDRESS_BOARD_B_USB_VID = 700,
    MODBUS_ADDRESS_BOARD_B_USB_PID = 701,
    MODBUS_ADDRESS_MAX,
} MODBUS_ADDRESS_IO_BOARD_TABLE;

typedef enum {
	MODBUS_MANAGER_QUERY_TYPE_SLAVE_ID = 0,
	MODBUS_MANAGER_QUERY_TYPE_FUNC_ID,
    MODBUS_MANAGER_QUERY_TYPE_REG_ADDR_HIGH,
    MODBUS_MANAGER_QUERY_TYPE_REG_ADDR_LOW,
    MODBUS_MANAGER_QUERY_TYPE_QUANTITY_HIGH,
    MODBUS_MANAGER_QUERY_TYPE_QUANTITY_LOW,
    MODBUS_MANAGER_QUERY_TYPE_CRC_HIGH,
    MODBUS_MANAGER_QUERY_TYPE_CRC_LOW,
    MODBUS_MANAGER_QUERY_TYPE_MAX,
} MODBUS_MANAGER_QUERY_TYPE;

int modbus_manager_init(void);
int modbus_manager_deinit(void);
int modbus_manager_flush(void);

/* modbus slave */
int modbus_manager_receive(uint8_t *req);
int modbus_manager_send(uint8_t *req, int req_len);
int modbus_manager_set_slave(uint8_t slaveID);

#define MODBUS_GPIO_Output_0           "GPIO_Output_0"
#define MODBUS_GPIO_Output_1           "GPIO_Output_1"
#define MODBUS_GPIO_Output_2           "GPIO_Output_2"
#define MODBUS_GPIO_Output_3           "GPIO_Output_3"
#define MODBUS_GPIO_Output_4           "GPIO_Output_4"
#define MODBUS_GPIO_Output_5           "GPIO_Output_5"
#define MODBUS_GPIO_Output_6           "GPIO_Output_6"
#define MODBUS_GPIO_Output_7           "GPIO_Output_7"

#define MODBUS_GPIO_Input_0            "GPIO_Input_0"
#define MODBUS_GPIO_Input_1            "GPIO_Input_1"
#define MODBUS_GPIO_Input_2            "GPIO_Input_2"
#define MODBUS_GPIO_Input_3            "GPIO_Input_3"
#define MODBUS_GPIO_Input_4            "GPIO_Input_4"
#define MODBUS_GPIO_Input_5            "GPIO_Input_5"
#define MODBUS_GPIO_Input_6            "GPIO_Input_6"
#define MODBUS_GPIO_Input_7            "GPIO_Input_7"

#define MODBUS_BOARD_A_USB_VID         "BOARD_A_USB_VID"
#define MODBUS_BOARD_A_USB_PID         "BOARD_A_USB_PID"
#define MODBUS_BOARD_B_USB_VID         "BOARD_B_USB_VID"
#define MODBUS_BOARD_B_USB_PID         "BOARD_B_USB_PID"

#define MODBUS_Setting_PWM_Frequence   "Setting_PWM_Frequence"
#define MODBUS_PWM_0_Duty              "PWM_0_Duty"
#define MODBUS_PWM_1_Duty              "PWM_1_Duty"
#define MODBUS_PWM_2_Duty              "PWM_2_Duty"
#define MODBUS_PWM_3_Duty              "PWM_3_Duty"
#define MODBUS_PWM_4_Duty              "PWM_4_Duty"
#define MODBUS_PWM_5_Duty              "PWM_5_Duty"
#define MODBUS_PWM_6_Duty              "PWM_6_Duty"
#define MODBUS_PWM_7_Duty              "PWM_7_Duty"

#define MODBUS_Capture_0_Duty          "Capture_0_Duty"
#define MODBUS_Capture_1_Duty          "Capture_1_Duty"
#define MODBUS_Capture_2_Duty          "Capture_2_Duty"
#define MODBUS_Capture_3_Duty          "Capture_3_Duty"
#define MODBUS_Capture_4_Duty          "Capture_4_Duty"
#define MODBUS_Capture_5_Duty          "Capture_5_Duty"
#define MODBUS_Capture_6_Duty          "Capture_6_Duty"
#define MODBUS_Capture_7_Duty          "Capture_7_Duty"

#define MODBUS_Capture_0_Frequency     "Capture_0_Frequency"
#define MODBUS_Capture_1_Frequency     "Capture_1_Frequency"
#define MODBUS_Capture_2_Frequency     "Capture_2_Frequency"
#define MODBUS_Capture_3_Frequency     "Capture_3_Frequency"
#define MODBUS_Capture_4_Frequency     "Capture_4_Frequency"
#define MODBUS_Capture_5_Frequency     "Capture_5_Frequency"
#define MODBUS_Capture_6_Frequency     "Capture_6_Frequency"
#define MODBUS_Capture_7_Frequency     "Capture_7_Frequency"

#define MODBUS_Capture_0_Duty_HZ       "Capture_0_Duty_HZ"
#define MODBUS_Capture_1_Duty_HZ       "Capture_1_Duty_HZ"
#define MODBUS_Capture_2_Duty_HZ       "Capture_2_Duty_HZ"
#define MODBUS_Capture_3_Duty_HZ       "Capture_3_Duty_HZ"
#define MODBUS_Capture_4_Duty_HZ       "Capture_4_Duty_HZ"
#define MODBUS_Capture_5_Duty_HZ       "Capture_5_Duty_HZ"
#define MODBUS_Capture_6_Duty_HZ       "Capture_6_Duty_HZ"
#define MODBUS_Capture_7_Duty_HZ       "Capture_7_Duty_HZ"

#define MODBUS_AD74416H_CH_A_SET_MODE   "AD74416H_CH_A_SET_MODE"
#define MODBUS_AD74416H_CH_B_SET_MODE   "AD74416H_CH_B_SET_MODE"
#define MODBUS_AD74416H_CH_C_SET_MODE   "AD74416H_CH_C_SET_MODE"
#define MODBUS_AD74416H_CH_D_SET_MODE   "AD74416H_CH_D_SET_MODE"

#define MODBUS_AD74416H_CH_A_VOLTAGE_OUT_MAX_CURRENT_MA       "AD74416H_CH_A_VOLTAGE_OUT_MAX_CURRENT_MA"
#define MODBUS_AD74416H_CH_B_VOLTAGE_OUT_MAX_CURRENT_MA       "AD74416H_CH_B_VOLTAGE_OUT_MAX_CURRENT_MA"
#define MODBUS_AD74416H_CH_C_VOLTAGE_OUT_MAX_CURRENT_MA       "AD74416H_CH_C_VOLTAGE_OUT_MAX_CURRENT_MA"
#define MODBUS_AD74416H_CH_D_VOLTAGE_OUT_MAX_CURRENT_MA       "AD74416H_CH_D_VOLTAGE_OUT_MAX_CURRENT_MA"

#define MODBUS_AD74416H_CH_A_CURRENT_INPUT_MAX_CURRENT_MA     "AD74416H_CH_A_CURRENT_INPUT_MAX_CURRENT_MA"
#define MODBUS_AD74416H_CH_B_CURRENT_INPUT_MAX_CURRENT_MA     "AD74416H_CH_B_CURRENT_INPUT_MAX_CURRENT_MA"
#define MODBUS_AD74416H_CH_C_CURRENT_INPUT_MAX_CURRENT_MA     "AD74416H_CH_C_CURRENT_INPUT_MAX_CURRENT_MA"
#define MODBUS_AD74416H_CH_D_CURRENT_INPUT_MAX_CURRENT_MA     "AD74416H_CH_D_CURRENT_INPUT_MAX_CURRENT_MA"

#define MODBUS_AD74416H_CH_A_VOLTAGE_OUTPUT_V     "AD74416H_CH_A_VOLTAGE_OUTPUT_V"
#define MODBUS_AD74416H_CH_B_VOLTAGE_OUTPUT_V     "AD74416H_CH_B_VOLTAGE_OUTPUT_V"
#define MODBUS_AD74416H_CH_C_VOLTAGE_OUTPUT_V     "AD74416H_CH_C_VOLTAGE_OUTPUT_V"
#define MODBUS_AD74416H_CH_D_VOLTAGE_OUTPUT_V     "AD74416H_CH_D_VOLTAGE_OUTPUT_V"

#define MODBUS_AD74416H_CH_A_CURRENT_OUTPUT_MA     "AD74416H_CH_A_CURRENT_OUTPUT_MA"
#define MODBUS_AD74416H_CH_B_CURRENT_OUTPUT_MA     "AD74416H_CH_B_CURRENT_OUTPUT_MA"
#define MODBUS_AD74416H_CH_C_CURRENT_OUTPUT_MA     "AD74416H_CH_C_CURRENT_OUTPUT_MA"
#define MODBUS_AD74416H_CH_D_CURRENT_OUTPUT_MA     "AD74416H_CH_D_CURRENT_OUTPUT_MA"

#define MODBUS_AD74416H_CH_A_VOLTAGE_INPUT     "AD74416H_CH_A_VOLTAGE_INPUT"
#define MODBUS_AD74416H_CH_B_VOLTAGE_INPUT     "AD74416H_CH_B_VOLTAGE_INPUT"
#define MODBUS_AD74416H_CH_C_VOLTAGE_INPUT     "AD74416H_CH_C_VOLTAGE_INPUT"
#define MODBUS_AD74416H_CH_D_VOLTAGE_INPUT     "AD74416H_CH_D_VOLTAGE_INPUT"

#define MODBUS_AD74416H_CH_A_CURRENT_INPUT_MA     "AD74416H_CH_A_CURRENT_INPUT_MA"
#define MODBUS_AD74416H_CH_B_CURRENT_INPUT_MA     "AD74416H_CH_B_CURRENT_INPUT_MA"
#define MODBUS_AD74416H_CH_C_CURRENT_INPUT_MA     "AD74416H_CH_C_CURRENT_INPUT_MA"
#define MODBUS_AD74416H_CH_D_CURRENT_INPUT_MA     "AD74416H_CH_D_CURRENT_INPUT_MA"

#define MODBUS_SET_BAUDRATE "SET_BAUDRATE"
#define MODBUS_SET_DATABITS "SET_DATABITS"
#define MODBUS_SET_PARITY "SET_PARITY"
#define MODBUS_SET_STOPBITS "SET_STOPBITS"
#define MODBUS_SET_PWM_FREQ "SET_PWM_FREQ"

#define MODBUS_SET_PWM_0_DUTY "SET_PWM_0_DUTY"
#define MODBUS_SET_PWM_1_DUTY "SET_PWM_1_DUTY"
#define MODBUS_SET_PWM_2_DUTY "SET_PWM_2_DUTY"
#define MODBUS_SET_PWM_3_DUTY "SET_PWM_3_DUTY"
#define MODBUS_SET_PWM_4_DUTY "SET_PWM_4_DUTY"
#define MODBUS_SET_PWM_5_DUTY "SET_PWM_5_DUTY"
#define MODBUS_SET_PWM_6_DUTY "SET_PWM_6_DUTY"
#define MODBUS_SET_PWM_7_DUTY "SET_PWM_7_DUTY"

#define MODBUS_CAPTURE_PWM_0_DUTY "CAPTURE_PWM_0_DUTY"
#define MODBUS_CAPTURE_PWM_1_DUTY "CAPTURE_PWM_1_DUTY"
#define MODBUS_CAPTURE_PWM_2_DUTY "CAPTURE_PWM_2_DUTY"
#define MODBUS_CAPTURE_PWM_3_DUTY "CAPTURE_PWM_3_DUTY"
#define MODBUS_CAPTURE_PWM_4_DUTY "CAPTURE_PWM_4_DUTY"
#define MODBUS_CAPTURE_PWM_5_DUTY "CAPTURE_PWM_5_DUTY"
#define MODBUS_CAPTURE_PWM_6_DUTY "CAPTURE_PWM_6_DUTY"
#define MODBUS_CAPTURE_PWM_7_DUTY "CAPTURE_PWM_7_DUTY"

#define MODBUS_CAPTURE_PWM_0_FREQ "CAPTURE_PWM_0_FREQ"
#define MODBUS_CAPTURE_PWM_1_FREQ "CAPTURE_PWM_1_FREQ"
#define MODBUS_CAPTURE_PWM_2_FREQ "CAPTURE_PWM_2_FREQ"
#define MODBUS_CAPTURE_PWM_3_FREQ "CAPTURE_PWM_3_FREQ"
#define MODBUS_CAPTURE_PWM_4_FREQ "CAPTURE_PWM_4_FREQ"
#define MODBUS_CAPTURE_PWM_5_FREQ "CAPTURE_PWM_5_FREQ"
#define MODBUS_CAPTURE_PWM_6_FREQ "CAPTURE_PWM_6_FREQ"
#define MODBUS_CAPTURE_PWM_7_FREQ "CAPTURE_PWM_7_FREQ"

#define MODBUS_CAPTURE_PWM_0_WIDTH_TIME "CAPTURE_PWM_0_WIDTH_TIME"
#define MODBUS_CAPTURE_PWM_1_WIDTH_TIME "CAPTURE_PWM_1_WIDTH_TIME"
#define MODBUS_CAPTURE_PWM_2_WIDTH_TIME "CAPTURE_PWM_2_WIDTH_TIME"
#define MODBUS_CAPTURE_PWM_3_WIDTH_TIME "CAPTURE_PWM_3_WIDTH_TIME"
#define MODBUS_CAPTURE_PWM_4_WIDTH_TIME "CAPTURE_PWM_4_WIDTH_TIME"
#define MODBUS_CAPTURE_PWM_5_WIDTH_TIME "CAPTURE_PWM_5_WIDTH_TIME"
#define MODBUS_CAPTURE_PWM_6_WIDTH_TIME "CAPTURE_PWM_6_WIDTH_TIME"
#define MODBUS_CAPTURE_PWM_7_WIDTH_TIME "CAPTURE_PWM_7_WIDTH_TIME"

#define MODBUS_AD7124_CH_0_RESISTOR "AD7124_CH_0_RESISTOR"
#define MODBUS_AD7124_CH_1_RESISTOR "AD7124_CH_1_RESISTOR"
#define MODBUS_AD7124_CH_2_RESISTOR "AD7124_CH_2_RESISTOR"
#define MODBUS_AD7124_CH_3_RESISTOR "AD7124_CH_3_RESISTOR"
#define MODBUS_AD7124_CH_4_RESISTOR "AD7124_CH_4_RESISTOR"
#define MODBUS_AD7124_CH_5_RESISTOR "AD7124_CH_5_RESISTOR"
#define MODBUS_AD7124_CH_6_RESISTOR "AD7124_CH_6_RESISTOR"
#define MODBUS_AD7124_CH_7_RESISTOR "AD7124_CH_7_RESISTOR"

#define MODBUS_AD7124_CH_0_TEMPERATURE "AD7124_CH_0_TEMPERATURE"
#define MODBUS_AD7124_CH_1_TEMPERATURE "AD7124_CH_1_TEMPERATURE"
#define MODBUS_AD7124_CH_2_TEMPERATURE "AD7124_CH_2_TEMPERATURE"
#define MODBUS_AD7124_CH_3_TEMPERATURE "AD7124_CH_3_TEMPERATURE"
#define MODBUS_AD7124_CH_4_TEMPERATURE "AD7124_CH_4_TEMPERATURE"
#define MODBUS_AD7124_CH_5_TEMPERATURE "AD7124_CH_5_TEMPERATURE"
#define MODBUS_AD7124_CH_6_TEMPERATURE "AD7124_CH_6_TEMPERATURE"
#define MODBUS_AD7124_CH_7_TEMPERATURE "AD7124_CH_7_TEMPERATURE"

typedef enum {
    MODBUS_TYPE_INT16,
    MODBUS_TYPE_UINT16,
    MODBUS_TYPE_INT32,
    MODBUS_TYPE_UINT32,
    MODBUS_TYPE_FLOAT32,
    MODBUS_TYPE_UINT64,
    MODBUS_TYPE_UINT16_LOWBYTE,
    MODBUS_TYPE_UINT16_HIGHBYTE,
    MODBUS_TYPE_INVALID = 0xDEAD,
} ModbusTypes_t;

typedef enum {
    MODBUS_FUNC_INVALID                       = 0x00, // Invalid function code
    MODBUS_FUNC_READ_COILS                    = 0x01, // Read Coils
    MODBUS_FUNC_READ_DISCRETE_INPUTS          = 0x02, // Read Discrete Inputs
    MODBUS_FUNC_READ_HOLDING_REGISTERS        = 0x03, // Read Holding Registers
    MODBUS_FUNC_READ_INPUT_REGISTERS          = 0x04, // Read Input Registers
    MODBUS_FUNC_WRITE_SINGLE_COIL             = 0x05, // Write Single Coil
    MODBUS_FUNC_WRITE_SINGLE_REGISTER         = 0x06, // Write Single Register
    MODBUS_FUNC_WRITE_MULTIPLE_COILS          = 0x0F, // Write Multiple Coils
    MODBUS_FUNC_WRITE_MULTIPLE_REGISTERS      = 0x10, // Write Multiple Registers
    MODBUS_FUNC_READ_WRITE_MULTIPLE_REGISTERS = 0x17  // Read/Write Multiple Registers
} MODBUS_FUNC_CODE;

typedef struct ModbusToMapping {
    ModbusTypes_t   value_type;
    char*           describe;
    uint16_t        address;
    uint16_t        hid_product;
    uint16_t        hid_address;
    MODBUS_FUNC_CODE  function_code;
} ModbusToMapping;

static const ModbusToMapping _MODBUS_IO_BOARD_MAPPING_LIST[] = {
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Output_0, MODBUS_ADDRESS_GPIO_OUTPUT_0, 0xA2, DK_MODBUS_GPIO_OUTPUT_0, MODBUS_FUNC_READ_WRITE_MULTIPLE_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Output_1, MODBUS_ADDRESS_GPIO_OUTPUT_1, 0xA2, DK_MODBUS_GPIO_OUTPUT_1, MODBUS_FUNC_READ_WRITE_MULTIPLE_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Output_2, MODBUS_ADDRESS_GPIO_OUTPUT_2, 0xA2, DK_MODBUS_GPIO_OUTPUT_2, MODBUS_FUNC_READ_WRITE_MULTIPLE_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Output_3, MODBUS_ADDRESS_GPIO_OUTPUT_3, 0xA2, DK_MODBUS_GPIO_OUTPUT_3, MODBUS_FUNC_READ_WRITE_MULTIPLE_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Output_4, MODBUS_ADDRESS_GPIO_OUTPUT_4, 0xA2, DK_MODBUS_GPIO_OUTPUT_4, MODBUS_FUNC_READ_WRITE_MULTIPLE_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Output_5, MODBUS_ADDRESS_GPIO_OUTPUT_5, 0xA2, DK_MODBUS_GPIO_OUTPUT_5, MODBUS_FUNC_READ_WRITE_MULTIPLE_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Output_6, MODBUS_ADDRESS_GPIO_OUTPUT_6, 0xA2, DK_MODBUS_GPIO_OUTPUT_6, MODBUS_FUNC_READ_WRITE_MULTIPLE_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Output_7, MODBUS_ADDRESS_GPIO_OUTPUT_7, 0xA2, DK_MODBUS_GPIO_OUTPUT_7, MODBUS_FUNC_READ_WRITE_MULTIPLE_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Input_0, MODBUS_ADDRESS_GPIO_INPUT_0, 0xA2, DK_MODBUS_GPIO_INPUT_0, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Input_1, MODBUS_ADDRESS_GPIO_INPUT_1, 0xA2, DK_MODBUS_GPIO_INPUT_1, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Input_2, MODBUS_ADDRESS_GPIO_INPUT_2, 0xA2, DK_MODBUS_GPIO_INPUT_2, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Input_3, MODBUS_ADDRESS_GPIO_INPUT_3, 0xA2, DK_MODBUS_GPIO_INPUT_3, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Input_4, MODBUS_ADDRESS_GPIO_INPUT_4, 0xA2, DK_MODBUS_GPIO_INPUT_4, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Input_5, MODBUS_ADDRESS_GPIO_INPUT_5, 0xA2, DK_MODBUS_GPIO_INPUT_5, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Input_6, MODBUS_ADDRESS_GPIO_INPUT_6, 0xA2, DK_MODBUS_GPIO_INPUT_6, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_GPIO_Input_7, MODBUS_ADDRESS_GPIO_INPUT_7, 0xA2, DK_MODBUS_GPIO_INPUT_7, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_AD74416H_CH_A_SET_MODE, MODBUS_ADDRESS_AD74416H_CH_A_SET_MODE, 0xA2, DK_MODBUS_AD74416H_SET_MODE_CH_A, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_AD74416H_CH_B_SET_MODE, MODBUS_ADDRESS_AD74416H_CH_B_SET_MODE, 0xA2, DK_MODBUS_AD74416H_SET_MODE_CH_B, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_AD74416H_CH_C_SET_MODE, MODBUS_ADDRESS_AD74416H_CH_C_SET_MODE, 0xA2, DK_MODBUS_AD74416H_SET_MODE_CH_C, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_AD74416H_CH_D_SET_MODE, MODBUS_ADDRESS_AD74416H_CH_D_SET_MODE, 0xA2, DK_MODBUS_AD74416H_SET_MODE_CH_D, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_A_VOLTAGE_OUT_MAX_CURRENT_MA, MODBUS_ADDRESS_AD74416H_CH_A_VOLTAGE_OUT_MAX_CURRENT, 0xA2, DK_MODBUS_AD74416H_VOUT_CLIMIT_CH_A, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_B_VOLTAGE_OUT_MAX_CURRENT_MA, MODBUS_ADDRESS_AD74416H_CH_B_VOLTAGE_OUT_MAX_CURRENT, 0xA2, DK_MODBUS_AD74416H_VOUT_CLIMIT_CH_B, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_C_VOLTAGE_OUT_MAX_CURRENT_MA, MODBUS_ADDRESS_AD74416H_CH_C_VOLTAGE_OUT_MAX_CURRENT, 0xA2, DK_MODBUS_AD74416H_VOUT_CLIMIT_CH_C, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_D_VOLTAGE_OUT_MAX_CURRENT_MA, MODBUS_ADDRESS_AD74416H_CH_D_VOLTAGE_OUT_MAX_CURRENT, 0xA2, DK_MODBUS_AD74416H_VOUT_CLIMIT_CH_D, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_AD74416H_CH_A_CURRENT_INPUT_MAX_CURRENT_MA, MODBUS_ADDRESS_AD74416H_CH_A_CURRENT_INPUT_MAX_CURRENT, 0xA2, DK_MODBUS_AD74416H_CIN_CLIMIT_CH_A, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_AD74416H_CH_B_CURRENT_INPUT_MAX_CURRENT_MA, MODBUS_ADDRESS_AD74416H_CH_B_CURRENT_INPUT_MAX_CURRENT, 0xA2, DK_MODBUS_AD74416H_CIN_CLIMIT_CH_B, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_AD74416H_CH_C_CURRENT_INPUT_MAX_CURRENT_MA, MODBUS_ADDRESS_AD74416H_CH_C_CURRENT_INPUT_MAX_CURRENT, 0xA2, DK_MODBUS_AD74416H_CIN_CLIMIT_CH_C, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_AD74416H_CH_D_CURRENT_INPUT_MAX_CURRENT_MA, MODBUS_ADDRESS_AD74416H_CH_D_CURRENT_INPUT_MAX_CURRENT, 0xA2, DK_MODBUS_AD74416H_CIN_CLIMIT_CH_D, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_A_VOLTAGE_OUTPUT_V, MODBUS_ADDRESS_AD74416H_CH_A_VOLTAGE_OUTPUT_V, 0xA2, DK_MODBUS_AD74416H_VOLTAGE_OUTPUT_CH_A, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_B_VOLTAGE_OUTPUT_V, MODBUS_ADDRESS_AD74416H_CH_B_VOLTAGE_OUTPUT_V, 0xA2, DK_MODBUS_AD74416H_VOLTAGE_OUTPUT_CH_B, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_C_VOLTAGE_OUTPUT_V, MODBUS_ADDRESS_AD74416H_CH_C_VOLTAGE_OUTPUT_V, 0xA2, DK_MODBUS_AD74416H_VOLTAGE_OUTPUT_CH_C, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_D_VOLTAGE_OUTPUT_V, MODBUS_ADDRESS_AD74416H_CH_D_VOLTAGE_OUTPUT_V, 0xA2, DK_MODBUS_AD74416H_VOLTAGE_OUTPUT_CH_D, MODBUS_FUNC_READ_HOLDING_REGISTERS},   
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_A_CURRENT_OUTPUT_MA, MODBUS_ADDRESS_AD74416H_CH_A_CURRENT_OUTPUT, 0xA2, DK_MODBUS_AD74416H_CURRENT_OUTPUT_CH_A, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_B_CURRENT_OUTPUT_MA, MODBUS_ADDRESS_AD74416H_CH_B_CURRENT_OUTPUT, 0xA2, DK_MODBUS_AD74416H_CURRENT_OUTPUT_CH_B, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_C_CURRENT_OUTPUT_MA, MODBUS_ADDRESS_AD74416H_CH_C_CURRENT_OUTPUT, 0xA2, DK_MODBUS_AD74416H_CURRENT_OUTPUT_CH_C, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_D_CURRENT_OUTPUT_MA, MODBUS_ADDRESS_AD74416H_CH_D_CURRENT_OUTPUT, 0xA2, DK_MODBUS_AD74416H_CURRENT_OUTPUT_CH_D, MODBUS_FUNC_READ_HOLDING_REGISTERS}, 
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_A_VOLTAGE_INPUT, MODBUS_ADDRESS_AD74416H_CH_A_VOLTAGE, 0xA2, DK_MODBUS_AD74416H_GET_VOLTAGE_INPUT_CH_A, MODBUS_FUNC_READ_HOLDING_REGISTERS}, 
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_B_VOLTAGE_INPUT, MODBUS_ADDRESS_AD74416H_CH_B_VOLTAGE, 0xA2, DK_MODBUS_AD74416H_GET_VOLTAGE_INPUT_CH_B, MODBUS_FUNC_READ_HOLDING_REGISTERS}, 
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_C_VOLTAGE_INPUT, MODBUS_ADDRESS_AD74416H_CH_C_VOLTAGE, 0xA2, DK_MODBUS_AD74416H_GET_VOLTAGE_INPUT_CH_C, MODBUS_FUNC_READ_HOLDING_REGISTERS}, 
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_D_VOLTAGE_INPUT, MODBUS_ADDRESS_AD74416H_CH_D_VOLTAGE, 0xA2, DK_MODBUS_AD74416H_GET_VOLTAGE_INPUT_CH_D, MODBUS_FUNC_READ_HOLDING_REGISTERS}, 
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_A_CURRENT_INPUT_MA, MODBUS_ADDRESS_AD74416H_CH_A_CURRENT, 0xA2, DK_MODBUS_AD74416H_GET_CURRENT_INPUT_CH_A, MODBUS_FUNC_READ_HOLDING_REGISTERS}, 
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_B_CURRENT_INPUT_MA, MODBUS_ADDRESS_AD74416H_CH_B_CURRENT, 0xA2, DK_MODBUS_AD74416H_GET_CURRENT_INPUT_CH_B, MODBUS_FUNC_READ_HOLDING_REGISTERS}, 
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_C_CURRENT_INPUT_MA, MODBUS_ADDRESS_AD74416H_CH_C_CURRENT, 0xA2, DK_MODBUS_AD74416H_GET_CURRENT_INPUT_CH_C, MODBUS_FUNC_READ_HOLDING_REGISTERS}, 
{MODBUS_TYPE_INT32, MODBUS_AD74416H_CH_D_CURRENT_INPUT_MA, MODBUS_ADDRESS_AD74416H_CH_D_CURRENT, 0xA2, DK_MODBUS_AD74416H_GET_CURRENT_INPUT_CH_D, MODBUS_FUNC_READ_HOLDING_REGISTERS}, 
{MODBUS_TYPE_UINT16, MODBUS_BOARD_A_USB_VID, MODBUS_ADDRESS_BOARD_A_USB_VID, 0xA2, 0, MODBUS_FUNC_READ_HOLDING_REGISTERS}, 
{MODBUS_TYPE_UINT16, MODBUS_BOARD_A_USB_PID, MODBUS_ADDRESS_BOARD_A_USB_PID, 0xA2, 0, MODBUS_FUNC_READ_HOLDING_REGISTERS},  
{MODBUS_TYPE_UINT16, MODBUS_SET_BAUDRATE, MODBUS_ADDRESS_SET_BAUDRATE, 0xA3, 0x11, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_SET_DATABITS, MODBUS_ADDRESS_SET_DATABITS, 0xA3, 0x12, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_SET_PARITY, MODBUS_ADDRESS_SET_PARITY, 0xA3, 0x13, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_SET_STOPBITS, MODBUS_ADDRESS_SET_STOPBITS, 0xA3, 0x14, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT32, MODBUS_SET_PWM_FREQ, MODBUS_ADDRESS_SET_PWM_FREQ, 0xA3, DK_MODBUS_PWM_FREQUENCY, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_SET_PWM_0_DUTY, MODBUS_ADDRESS_SET_PWM_0_DUTY, 0xA3, DK_MODBUS_PWM_DUTY_0, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_SET_PWM_1_DUTY, MODBUS_ADDRESS_SET_PWM_1_DUTY, 0xA3, DK_MODBUS_PWM_DUTY_1, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_SET_PWM_2_DUTY, MODBUS_ADDRESS_SET_PWM_2_DUTY, 0xA3, DK_MODBUS_PWM_DUTY_2, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_SET_PWM_3_DUTY, MODBUS_ADDRESS_SET_PWM_3_DUTY, 0xA3, DK_MODBUS_PWM_DUTY_3, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_SET_PWM_4_DUTY, MODBUS_ADDRESS_SET_PWM_4_DUTY, 0xA3, DK_MODBUS_PWM_DUTY_4, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_SET_PWM_5_DUTY, MODBUS_ADDRESS_SET_PWM_5_DUTY, 0xA3, DK_MODBUS_PWM_DUTY_5, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_SET_PWM_6_DUTY, MODBUS_ADDRESS_SET_PWM_6_DUTY, 0xA3, DK_MODBUS_PWM_DUTY_6, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_SET_PWM_7_DUTY, MODBUS_ADDRESS_SET_PWM_7_DUTY, 0xA3, DK_MODBUS_PWM_DUTY_7, MODBUS_FUNC_WRITE_SINGLE_REGISTER},
{MODBUS_TYPE_UINT16, MODBUS_CAPTURE_PWM_0_DUTY, MODBUS_ADDRESS_CAPTURE_PWM_0_DUTY, 0xA3, DK_MODBUS_CAP_PWM_DUTY_0, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_CAPTURE_PWM_1_DUTY, MODBUS_ADDRESS_CAPTURE_PWM_1_DUTY, 0xA3, DK_MODBUS_CAP_PWM_DUTY_1, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_CAPTURE_PWM_2_DUTY, MODBUS_ADDRESS_CAPTURE_PWM_2_DUTY, 0xA3, DK_MODBUS_CAP_PWM_DUTY_2, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_CAPTURE_PWM_3_DUTY, MODBUS_ADDRESS_CAPTURE_PWM_3_DUTY, 0xA3, DK_MODBUS_CAP_PWM_DUTY_3, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_CAPTURE_PWM_4_DUTY, MODBUS_ADDRESS_CAPTURE_PWM_4_DUTY, 0xA3, DK_MODBUS_CAP_PWM_DUTY_4, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_CAPTURE_PWM_5_DUTY, MODBUS_ADDRESS_CAPTURE_PWM_5_DUTY, 0xA3, DK_MODBUS_CAP_PWM_DUTY_5, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_CAPTURE_PWM_6_DUTY, MODBUS_ADDRESS_CAPTURE_PWM_6_DUTY, 0xA3, DK_MODBUS_CAP_PWM_DUTY_6, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_CAPTURE_PWM_7_DUTY, MODBUS_ADDRESS_CAPTURE_PWM_7_DUTY, 0xA3, DK_MODBUS_CAP_PWM_DUTY_7, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_0_FREQ, MODBUS_ADDRESS_CAPTURE_PWM_0_FREQ, 0xA3, DK_MODBUS_CAP_PWM_FREQ_0, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_1_FREQ, MODBUS_ADDRESS_CAPTURE_PWM_1_FREQ, 0xA3, DK_MODBUS_CAP_PWM_FREQ_1, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_2_FREQ, MODBUS_ADDRESS_CAPTURE_PWM_2_FREQ, 0xA3, DK_MODBUS_CAP_PWM_FREQ_2, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_3_FREQ, MODBUS_ADDRESS_CAPTURE_PWM_3_FREQ, 0xA3, DK_MODBUS_CAP_PWM_FREQ_3, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_4_FREQ, MODBUS_ADDRESS_CAPTURE_PWM_4_FREQ, 0xA3, DK_MODBUS_CAP_PWM_FREQ_4, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_5_FREQ, MODBUS_ADDRESS_CAPTURE_PWM_5_FREQ, 0xA3, DK_MODBUS_CAP_PWM_FREQ_5, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_6_FREQ, MODBUS_ADDRESS_CAPTURE_PWM_6_FREQ, 0xA3, DK_MODBUS_CAP_PWM_FREQ_6, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_7_FREQ, MODBUS_ADDRESS_CAPTURE_PWM_7_FREQ, 0xA3, DK_MODBUS_CAP_PWM_FREQ_7, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_0_WIDTH_TIME, MODBUS_ADDRESS_CAPTURE_PWM_0_PERIOD, 0xA3, DK_MODBUS_CAP_PWM_PULSE_WIDTH_0, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_1_WIDTH_TIME, MODBUS_ADDRESS_CAPTURE_PWM_1_PERIOD, 0xA3, DK_MODBUS_CAP_PWM_PULSE_WIDTH_1, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_2_WIDTH_TIME, MODBUS_ADDRESS_CAPTURE_PWM_2_PERIOD, 0xA3, DK_MODBUS_CAP_PWM_PULSE_WIDTH_2, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_3_WIDTH_TIME, MODBUS_ADDRESS_CAPTURE_PWM_3_PERIOD, 0xA3, DK_MODBUS_CAP_PWM_PULSE_WIDTH_3, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_4_WIDTH_TIME, MODBUS_ADDRESS_CAPTURE_PWM_4_PERIOD, 0xA3, DK_MODBUS_CAP_PWM_PULSE_WIDTH_4, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_5_WIDTH_TIME, MODBUS_ADDRESS_CAPTURE_PWM_5_PERIOD, 0xA3, DK_MODBUS_CAP_PWM_PULSE_WIDTH_5, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_6_WIDTH_TIME, MODBUS_ADDRESS_CAPTURE_PWM_6_PERIOD, 0xA3, DK_MODBUS_CAP_PWM_PULSE_WIDTH_6, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_CAPTURE_PWM_7_WIDTH_TIME, MODBUS_ADDRESS_CAPTURE_PWM_7_PERIOD, 0xA3, DK_MODBUS_CAP_PWM_PULSE_WIDTH_7, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_AD7124_CH_0_RESISTOR, MODBUS_ADDRESS_AD7124_CH_0_RESISTOR, 0xA3, DK_MODBUS_AD7124_GET_RESISTANCE_CH_0, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_AD7124_CH_1_RESISTOR, MODBUS_ADDRESS_AD7124_CH_1_RESISTOR, 0xA3, DK_MODBUS_AD7124_GET_RESISTANCE_CH_1, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_AD7124_CH_2_RESISTOR, MODBUS_ADDRESS_AD7124_CH_2_RESISTOR, 0xA3, DK_MODBUS_AD7124_GET_RESISTANCE_CH_2, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_AD7124_CH_3_RESISTOR, MODBUS_ADDRESS_AD7124_CH_3_RESISTOR, 0xA3, DK_MODBUS_AD7124_GET_RESISTANCE_CH_3, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_AD7124_CH_4_RESISTOR, MODBUS_ADDRESS_AD7124_CH_4_RESISTOR, 0xA3, DK_MODBUS_AD7124_GET_RESISTANCE_CH_4, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_AD7124_CH_5_RESISTOR, MODBUS_ADDRESS_AD7124_CH_5_RESISTOR, 0xA3, DK_MODBUS_AD7124_GET_RESISTANCE_CH_5, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_AD7124_CH_6_RESISTOR, MODBUS_ADDRESS_AD7124_CH_6_RESISTOR, 0xA3, DK_MODBUS_AD7124_GET_RESISTANCE_CH_6, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT32, MODBUS_AD7124_CH_7_RESISTOR, MODBUS_ADDRESS_AD7124_CH_7_RESISTOR, 0xA3, DK_MODBUS_AD7124_GET_RESISTANCE_CH_7, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_UINT16, MODBUS_BOARD_B_USB_VID, MODBUS_ADDRESS_BOARD_B_USB_VID, 0xA3, 0, MODBUS_FUNC_READ_HOLDING_REGISTERS}, 
{MODBUS_TYPE_UINT16, MODBUS_BOARD_B_USB_PID, MODBUS_ADDRESS_BOARD_B_USB_PID, 0xA3, 0, MODBUS_FUNC_READ_HOLDING_REGISTERS},
{MODBUS_TYPE_INVALID, NULL, 0, 0, 0, 0}
};

typedef enum {
	MODBUS_ADDRESS_RTC_YEAR = 2181,
    MODBUS_ADDRESS_RTC_MONTH = 2182,
    MODBUS_ADDRESS_RTC_DAY = 2183,
    MODBUS_ADDRESS_RTC_HOUR = 2184,
    MODBUS_ADDRESS_RTC_MIN = 2185,
    MODBUS_ADDRESS_RTC_SEC = 2186,
} MODBUS_ADDRESS_RTC_TABLE;

static const uint16_t _MODBUS_DATA_KEEP_LIST[] = {
    1001,
    1002,
    1003,
    1004,
    1005,
    1006,
    1007,
    2161, 
    2162,
    2163,
    2164,
    2165,
    2166,
    MODBUS_ADDRESS_RTC_YEAR,
    MODBUS_ADDRESS_RTC_MONTH,
    MODBUS_ADDRESS_RTC_DAY,
    MODBUS_ADDRESS_RTC_HOUR,
    MODBUS_ADDRESS_RTC_MIN,
    MODBUS_ADDRESS_RTC_SEC,
    5001,
    5002,
    5003,
    5004,
    5005,
    5006,
    5007,
    5008,
    5009,
    5010,
    5011,
    5026,
    5027,
    5028,
    5031,
    5032,
    5033,
    5034,
    5035,
    5051,
    5052,
    5053,
    5054,
    5055,
    5056,
    2801,
    5071,
    5072,
    5073,
    5074,
    5075,
    5076,
    5077,
    5078,
    5081,
    6001,
    6002,
    6003,
    6004,
    6005,
    6006,
    6007,
    6008,
    6009,
    6010,
    6011,
    6012,
    6013,
    6014,
    6031,
    6032,
    6033,
    6034,
    6035,
    6036,
    6037,
    6038,
    6039,
    6040,
    6041,
    6042,
    6043,
    6044,
    6045,
    6046,
    6061,
    6062,
    6071,
    6072,
    6073,
    6074,
    6101,
    6102,
    6103,
    6104,
    6105,
    6106,
    6107,
    6108,
    6109,
    6110,
    6111,
    6112,
    6113,
    6114,
    6131,
    6132,
    6133,
    6134,
    6135,
    6136,
    6137,
    6138,
    6139,
    6140,
    6141,
    6142,
    6143,
    6144,
    6145,
    6146,
    6161,
    6162,
    6171,
    6201,
    6202,
    6203,
    6204,
    6205,
    6206,
    6207,
    6208,
    6209,
    6210,
    6211,
    6212,
    6213,
    6214,
    6215,
    6216,
    6217,
    6218,
    6231,
    6232,
    6233,
    6234,
    6235,
    6236,
    6237,
    6238,
    6239,
    6240,
    6241,
    6242,
    6243,
    6244,
    6245,
    6246,
    6261,
    6262,
    6263,
    6271,
    6272,
    6301,
    6302,
    6303,
    6304,
    6305,
    6306,
    6307,
    6308,
    6309,
    6310,
    6311,
    6312,
    6313,
    6314,
    6315,
    6316,
    6317,
    6318,
    6331,
    6332,
    6333,
    6334,
    6335,
    6336,
    6337,
    6338,
    6339,
    6340,
    6341,
    6342,
    6343,
    6344,
    6345,
    6346,
    6371,
    6372,
    6402,
    6404,
    6406,
    6422,
    6424,
    6426,
    6428
};

modbus_mapping_t* modbus_manager_data_mapping_get(void);

// Callback function pointer type for modbus data updates
typedef int (*modbus_update_callback_t)(uint16_t address, uint8_t type, uint32_t value);
void modbus_manager_update_callback_setup(modbus_update_callback_t callback);

int modbus_manager_data_mapping_save(void);

#ifdef __cplusplus
}
#endif

#endif